---
- hosts: all
  user: orenault
  sudo: yes
  roles:
    - prep
    - ambari-agent
    - users

- hosts: db_server
  user: orenault
  sudo: yes
  roles:
    - db-server

- hosts: ambari_server
  user: orenault
  sudo: yes
  roles:
    - ambari-server
