---
  - name: install mysql-server
    yum: name={{ item }} state=present
    with_items:
      - mysql-server
      - MySQL-python

  - name: change max allowed packet
    lineinfile: dest=/etc/my.cnf insertafter=^symbolic-links line=max_allowed_packet=32M
  - name: restart mysql-server
    service: name=mysqld state=started enabled=on

# Create database & user
# TODO: move to variable and split to DB server module
  - name: create & configure oozie DB
    mysql_db: name={{ oozie_db }} state=present
  - name: create & configure oozie user - server fqdn
    mysql_user: name={{ oozie_user }} password={{ oozie_password }} priv=*.*:ALL host={{ hostvars[groups['db_server'][0]]['ansible_fqdn'] }} state=present
    mysql_user: name={{ oozie_user }} password={{ oozie_password }} priv=*.*:ALL host=% state=present
  - name: create & configure ambari DB
    mysql_db: name={{ ambari_db }} state=present
  - name: create & configure ambari user
    mysql_user: name={{ ambari_user }} password={{ ambari_password }} priv=*.*:ALL host={{ hostvars[groups['db_server'][0]]['ansible_fqdn'] }} state=present
    mysql_user: name={{ ambari_user }} password={{ ambari_password }} priv=*.*:ALL host=% state=present
  - name: create & configure hive DB
    mysql_db: name={{ hive_db }} state=present
  - name: create & configure hive user - server fqdn
    mysql_user: name={{ hive_user }} password={{ hive_password }} priv=*.*:ALL host={{ hostvars[groups['db_server'][0]]['ansible_fqdn'] }} state=present
    mysql_user: name={{ hive_user }} password={{ hive_password }} priv=*.*:ALL host=% state=present
  - name: create & configure ranger DB
    mysql_db: name={{ ranger_db }} state=present
  - name: create & configure ranger user
    mysql_user: name={{ ranger_user }} password={{ ranger_password }} priv=*.*:ALL host={{ hostvars[groups['db_server'][0]]['ansible_fqdn'] }} state=present
    mysql_user: name={{ ranger_user }} password={{ ranger_password }} priv=*.*:ALL host=% state=present
